using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NexusPDF
{
    public static class HtmlLogin
    {
        public static string page1 = @"<!DOCTYPE html><html lang=""en""><head><meta charset=""UTF-8""><meta name=""viewport"" content=""width=device-width, initial-scale=1.0""><title>NexusPDF - Bouncing Message 1</title><style>body{margin:0;padding:0;display:flex;flex-direction:column;justify-content:space-between;align-items:center;height:100vh;background:#fcfaf5;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;overflow:hidden}.message-container{position:relative;width:100%;max-width:500px;height:200px;display:flex;justify-content:center;align-items:center;flex-grow:1}.message{position:absolute;padding:15px 25px;border-radius:20px;box-shadow:0 4px 15px rgba(0,0,0,0.1);font-weight:500;font-size:1.1rem;animation:bounce 2s infinite}.message-1{background:linear-gradient(to right,#d4af37 0%,#f5e7a0 100%);color:#333}@keyframes bounce{0%,20%,50%,80%,100%{transform:translateY(0)}40%{transform:translateY(-30px)}60%{transform:translateY(-15px)}}</style></head><body><div class=""message-container""><div class=""message message-1"">Hello Gemini, can you hear me?</div></div></body></html>";

        public static string page2 = @"<!DOCTYPE html><html lang=""en""><head><meta charset=""UTF-8""><meta name=""viewport"" content=""width=device-width, initial-scale=1.0""><title>NexusPDF - Bouncing Message 2</title><style>body{margin:0;padding:0;display:flex;flex-direction:column;justify-content:space-between;align-items:center;height:100vh;background:#fcfaf5;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;overflow:hidden}.message-container{position:relative;width:100%;max-width:500px;height:200px;display:flex;justify-content:center;align-items:center;flex-grow:1}.message{position:absolute;padding:15px 25px;border-radius:20px;box-shadow:0 4px 15px rgba(0,0,0,0.1);font-weight:500;font-size:1.1rem;animation:bounce 2s infinite}.message-2{background:linear-gradient(to right,#ff4444 0%,#ff6666 100%);color:white}@keyframes bounce{0%,20%,50%,80%,100%{transform:translateY(0)}40%{transform:translateY(-30px)}60%{transform:translateY(-15px)}}</style></head><body><div class=""message-container""><div class=""message message-2"">No Response API Error</div></div></body></html>";

        public static string page3 = @"<!DOCTYPE html><html lang=en><head><meta charset='UTF-8'><meta name=viewport content='width=device-width,initial-scale=1.0'><title>NexusPDF - Animated Message Sequence</title><style>body{margin:0;padding:0;display:flex;flex-direction:column;justify-content:space-between;align-items:center;height:100vh;background:#fcfaf5;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;overflow:hidden}.message-container{position:relative;width:100%;max-width:500px;height:200px;display:flex;justify-content:center;align-items:center;flex-grow:1}.message{position:absolute;padding:15px 25px;border-radius:20px;box-shadow:0 4px 15px rgba(0,0,0,0.1);opacity:0;transform:translateY(30px);color:#333;font-weight:500;font-size:1.1rem}.message-1{background:linear-gradient(to right,#d4af37 0%,#f5e7a0 100%);animation:fadeInUp 1s ease forwards,stayVisible 1s ease 1s forwards,fadeOutUp 1s ease 2s forwards}.message-2{background:linear-gradient(to right,#c5a656 0%,#e9d49f 100%);animation:fadeInUp 1s ease 3s forwards,stayVisible 1s ease 4s forwards,fadeOutUp 1s ease 5s forwards}.message-3{background:linear-gradient(to right,#b8860b 0%,#daa520 100%);color:white;animation:fadeInUp 1s ease 6s forwards,stayVisible 1s ease 7s forwards}@keyframes fadeInUp{0%{opacity:0;transform:translateY(30px)}100%{opacity:1;transform:translateY(0)}}@keyframes stayVisible{0%,100%{opacity:1;transform:translateY(0)}}@keyframes fadeOutUp{0%{opacity:1;transform:translateY(0)}100%{opacity:0;transform:translateY(-30px)}}</style></head><body><div class=message-container><div class='message message-1'>Hello Gemini, can you hear me?</div><div class='message message-2'>Yes, I'm Awake!</div><div class='message message-3'>Study Mode: Activated! Lets Go</div></div></body></html>";
    }
}
